services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: testing
      POSTGRES_USER: ninjafire
      POSTGRES_PASSWORD: faxvax
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
